# Generated by Django 5.0.4 on 2024-04-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocesory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=20)),
                ('total_price', models.IntegerField()),
                ('flat_no', models.IntegerField()),
                ('discout_price', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('ON', 'ONLINE PAYMENT'), ('EMI', 'MONTHLY INSTALLMENT')], max_length=10)),
            ],
        ),
    ]
